#!/bin/bash
##
## Kyle Hotchkiss' Bash Configuration
## Settings work in both OSX and Linux.
##

# ----------------- #
# Contextual Prompt #
# ----------------- #
if [ "$TERM" != "dumb" ]; then
 if [ "$SSH_CONNECTION" ]; then
  export PS1="\[\e[37m\]{ \[\e[0m\]\[\e[1;31m\]\H \[\e[37m\]} \[\e[34m\]\W\[\e[0m\]: "

  alias ls='ls -F --color'

 else
  export PS1="\[\e[37m\]{ \[\e[0m\]\[\e[1;32m\]\h \[\e[37m\]} \[\e[34m\]\W\[\e[0m\]: "

  alias ls='ls -GF'

 fi
fi

# ------------------ #
# Output Corrections #
# ------------------ #
HISTCONTROL=ignoreboth; export HISTCONTROL
LC_COLLATE=C; export LC_COLLATE
